### ISSUE TITLE
كيف يمكن القيام بإعادة توجية المستخدم إلى صفحة تسجيل الدخول 

### ISSUE THREAD

**Issue by Nick390** [magic-coding/Firebase-MENADD2021#1]
تحية طيبه وبعد:
كيف يمكن القيام بإعادة توجيه المستخدم إذا كان غير مسجل الدخول على سبيل المثال إذا قام المستخدم عن قصد بمحاولة دخول الداشبورد بدون ان يسجل الدخول يقوم النظام بإعادة توجيهه إلى صفحة تسجيل الدخول بالإجبار ولا يمكن تجاوز هذه الخطوة والعكس ايضاً
وإستمر شروحاتك رائعه للغايه شكراً لك
@magic-coding

**Comment by malnafei** [comment]
مرحبا أخي الكريم، أعتذر على التأخير بالرد.
يمكنك إستخدام 
onAuthStateChanged 
بحيث تستمع لأي تغيير يحدث في الحساب مثل تسجيل الخروج.
هذا نموذج للكود:

```
firebase.auth().onAuthStateChanged((user) => {
        if (user) {
            var uid = user.uid;
            console.log(user.displayName);
            $("h4.text-dark.mb-4").text("Welcome, "+user.displayName);
            $(".fullName").text(user.displayName)
            $(".user").hide();
            $("#logout-user").show();
            var page = location.pathname.split('/').slice(-1)[0];
            if(page == "app.html") {

            } else {
                window.location = "./app.html"
            }

            // ...
        } else {
            // User is signed out
            // ...
        }
    });
```
